### PR TITLE
Add German translation

### PR DESCRIPTION
**Pull request by philippwiesemann**
Thanks!

### CODE REVIEW

**Comment by pmattern** [comment]
I'd suggest some minor improvements, stated by lines in files:

*lxqt-config-powermanagement_de.ts*
* 50: to depict ongoing procedures present participle isn't that common in German, rather simple present tense is used. So I'd suggest `Lade...`.
* 55: (counterpart to 50)
* 60: strictly speaking a dependent clause that should be separated by comma. Maybe better `Bei zu niedriger Ladung:`
* 93: same thing as in 60. Maybe better `Bei Leerlauf:`

*lxqt-powermanagement_de.ts*
* 14, 24: (see 50 above)
* 99 "Telefon" instead of "Phone", no?

Other than that GTM. Good work.

**Comment by philippwiesemann** [comment]
The commit was updated. Thanks for the suggestions.

**Comment by agaida** [comment]
GTM

**Comment by pmattern** [comment]
Thanks for contributing!

**Pull request merged**
