### PR TITLE
Idleness Watcher: rely on KIdleTime instead of XCB

### PR DESCRIPTION
**Pull request by paulolieuthier**
* Make it stop pretending it's a screensaver (leftover bits from razor).
* Get a little closer to Wayland!

### CODE REVIEW

**Comment by luis-pereira** [comment]
@paulolieuthier I was not aware of this.

**Comment by palinek** [comment]
GTM

**Comment by agaida** [comment]
GTM

**Comment by luis-pereira** [comment]
Is this going in before the release ?

**Comment by agaida** [comment]
Imho it should

**Comment by paulolieuthier** [comment]
This removes dependency on X11. And #36 made lxqt-powermanagement depend more on it. Once rebase, this PR will make lxqt-powermanagement depend on both X11 and KIdleTime. Is this what we want?

**Comment by luis-pereira** [comment]
@paulolieuthier https://github.com/lxde/lxqt-powermanagement/pull/36 never got it. It was replaced by lxde/liblxqt#98 and lxde/liblxqt#99.
Was this tested over a "long" period of time ?

**Comment by paulolieuthier** [comment]
s/#66/#99/

**Comment by luis-pereira** [comment]
@paulolieuthier Can't follow you ;)

**Comment by paulolieuthier** [comment]
Now I see the dependency was added in liblxqt, not here. Sorry! Let's merge it!

**Comment by paulolieuthier** [comment]
And yes, I tested for long periods of time. Someone else should test it as well to make sure it's solid.

**Comment by luis-pereira** [comment]
@paulolieuthier squash and merge.

**Comment by agaida** [comment]
@paulolieuthier would you or should i?

**Comment by paulolieuthier** [comment]
@agaida now remember to put it in caps on release notes.

**Comment by v-fox** [comment]
If it cease to emulate screensaver and provide org.freedesktop.ScreenSaver interface then how one supposed to inhibit monitor power-saving while using media players and gaming with gamepad (inputs of which are not recognized as activity for some reason) ?

And was it really inhibiting anything ? I'm using [Caffeine](https://launchpad.net/caffeine) which just stupidly inhibits when there are any fullscreen windows around since xscreensaver doesn't have the interface either and KDE's & Gnome's ones are dead.

**Pull request merged**
