### PR TITLE
Automatic brightness adjustments depending on battery state

### PR DESCRIPTION
**Pull request by h3xby**

### CODE REVIEW

**Comment by jleclanche** [comment]
Code looks good. I'll be  testing it on my laptop and see how that goes.

**Comment by paulolieuthier** [comment]
Some files miss license.

**Comment by h3xby** [comment]
Thanks. I updated commit. is it right license header?

**Comment by paulolieuthier** [comment]
@jleclanche please take a look at it. Does it need author information?

**Comment by jleclanche** [comment]
Presence of original author is up to the author himself.

**Comment by surlykke** [comment]
2015-09-02 7:31 GMT+02:00 Dmitry <notifications@github.com>:

> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/lxde/lxqt-powermanagement/pull/22
> Commit Summary
>
>    - Automatic brightness adjustments depending on battery state
>
> Gtm.

br. Chr.

**Comment by surlykke** [comment]
2015-09-04 16:54 GMT+02:00 christian@surlykke.dk <christian@surlykke.dk>:

> 2015-09-02 7:31 GMT+02:00 Dmitry <notifications@github.com>:
>
>> ------------------------------
>> You can view, comment on, or merge this pull request online at:
>>
>>   https://github.com/lxde/lxqt-powermanagement/pull/22
>> Commit Summary
>>
>>    - Automatic brightness adjustments depending on battery state
>>
>> Gtm.
>
>
After playing with it a bit more, I found that it doesn't integrate with
the brightness keys: If you set the brightness with
lxqt-config-powermanagement, close it, change the brightness with the
brightness keys, and then run lxqt-config-powermanagement, it sets the
brightness back to what it was when it was last closed.

That's a bit counter intuitive.

It would be nice if lxqt-config-powermanagement could read current
brightness when launched, and then set it's slider accordingly.

br. Chr.

**Comment by paulolieuthier** [comment]
@h3xby what do you think? Can you improve it?

**Comment by h3xby** [comment]
When lxqt-config-powermanagement is launched, it save settings automaticaly. If it read current brightness when launched and set it's slider accordingly, it will automaticaly save current brightness in settings, even when I only open config window and doesn't modify anything. I don't think this is correct behavior. I don't want my settings was modified by backlight keys directly.
Maybe it will be better, if connect "changed" signals after loading settings or block saving settings during loading settings, then it won't restore brightness when launched. What do you think?
Sorry for my english.

**Comment by paulolieuthier** [comment]
Here are my notes:
* Brightness on Battery is not being saved after a move the slider.
* Brightness should be set only on lxqt-powermanagemet's startup, not lxqt-config-powermanagement's.
* Both sliders should move to a separate page in lxqt-config-powermanagement and above them there should be a checkbox asking the user whether or not to automatically handle brightness on power state change.
* I find a bit confusing to distinguish between brightness and backlight. You are calling xcb functions and I'm not sure that's the best way. Take a look at how KDE does it: [brightness](https://quickgit.kde.org/?p=powerdevil.git&a=blob&h=0abcefe866ac5dc9d8bbe06457e3a597a1d426cd&hb=c8ec91a8097d676f9a35e18431b1a212359aeffe&f=daemon%2Fbackends%2Fupower%2Fxrandrbrightness.cpp) and [backlight](https://quickgit.kde.org/?p=powerdevil.git&a=blob&h=83efec1fdfa73cd5c6ae2c3d22c60f9f0029d358&hb=ecf23564bc81a418ebc6d45a97f0792097d4e5f5&f=daemon%2Fbackends%2Fupower%2Fbacklighthelper.cpp) (or the [directory](https://quickgit.kde.org/?p=powerdevil.git&a=tree&h=295c650916ed996423eba8127a130f5d5a552a58&hb=c8ec91a8097d676f9a35e18431b1a212359aeffe&f=daemon%2Fbackends%2Fupower)). What do you think?
* Your work is very appreciated. :smile:

**Comment by paulolieuthier** [comment]
Also: see the discussion in lxde/lxqt#36.

**Pull request closed without merging**
