### PR TITLE
WIP: Merge powermanagement autostart

### PR DESCRIPTION
**Pull request by agaida**
Please don't merge right now

### CODE REVIEW

**Comment by palinek** [comment]
GTM

(just the same for the COMPONENT...)

**Comment by palinek** [comment]
...and just to be sure. You removed "translations" files intentionaly... right?

**Comment by agaida** [comment]
Yes - the translations are never used for the autostarters and hopefully never will be used. So i stripped them.

**Comment by agaida** [comment]
Upps - they are used, but i would prefer not to use them anymore - had to investigate it

**Comment by palinek** [comment]
Now I remember....

We shouldn't get rid of the translations... they are used/shown in `lxqt-config-session` -> LXQt Modules.

**Comment by agaida** [comment]
and the question is if we could re-use the translations from the normal .desktop-files (if available) so we had to maintain only one set of translations

**Comment by agaida** [comment]
I guess the best way is very conservative - just migrate the current translations and descide later

**Comment by pmattern** [comment]
Agree. Nuking lxqt-common is rather complex so let's not put even more not so urgent stuff into it right now.

**Pull request closed without merging**
