### PR TITLE
Add Greek (el) translation

### PR DESCRIPTION
**Pull request by dglent**
Add the Greek (el) translation with the following files:
        config/translations/lxqt-config-powermanagement_el.desktop
        config/translations/lxqt-config-powermanagement_el.ts
        src/translations/lxqt-powermanagement_el.ts

### CODE REVIEW

**Comment by pmattern** [comment]
While looking through this commit I saw that key "Comment" was lacking in `./config/lxqt-config-powermanagement.desktop.in` which is fixed now.
You may want to adjust the Greek translation accordingly while at it and squash that change into the current commit / PR. If you should need help regarding the latter feel free to let me know.

**Comment by surlykke** [comment]
2015-08-30 12:33 GMT+02:00 Peter Mattern <notifications@github.com>:

> While looking through this commit I saw that key "Comment" was lacking in
> ./config/lxqt-config-powermanagement.desktop.in which is fixed now.
> You may want to adjust the Greek translation accordingly while at it and
> squash that change into the current commit / PR. If you should need help
> regarding the latter feel free to let me know.
>
> I have already pulled that one, so don't squash. Please make new PR.

- Chr.

**Comment by pmattern** [comment]
>  I have already pulled that one, so don't squash. Please make new PR.

Hm, not following here. This commit hasn't been merged yet. So what and where did you pull? And why shouldn't an eventual change be squashed into this commit, e. g. by running `git commit --amend`? This could very well be rebased and pushed to master as a single new one then, IMO.

**Comment by surlykke** [comment]
2015-08-30 13:00 GMT+02:00 Peter Mattern <notifications@github.com>:

> I have already pulled that one, so don't squash. Please make new PR.
>
> Hm, not following here. This commit hasn't been merged yet. So what and
> where did you pull? And why shouldn't an eventual change be squashed into
> this commit, e. g. by running git commit --amend? This could very well be
> rebased and pushed to master as a single new one then, IMO.
>
>  Whoops. I *thought* I had merged, but hmm, must have forgotten to click
one of the buttons. Please disregard what I wrote above. Sorry for the
noise.

- Chr.

**Comment by dglent** [comment]
Ok i updated the desktop file
Thank you

**Comment by pmattern** [comment]
Landed in ff4e3b7. Thanks.

In the meantime I saw that the translation as a whole is a bit buggy as e. g. topic "Previev" belonging to "Battery" in left pane isn't subject to translation at all.
Don't know what's the matter right now. You may want to stay tuned as a fix of that problem would of course have to be adopted by the distinct languages.

**Pull request closed without merging**
